spring:
  datasource:
    url: jdbc:mysql://10.246.0.54:3306/bip_op_lyx?serverTimezone=UTC&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: Lbx@db123456
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath*:mapper/*.xml
tengxun:
  accessKey: AKIDWmALGvrXoqa6MMaC0bw2rQM4WifLl7U4
  secretKey: VmmW1JrFRUIqyta1B5kAJEvSkmaAi9Zt
  area: ap-guangzhou
  bucketName: test-1301644127
  path: https://test-1301644127.cos.ap-guangzhou.myqcloud.com




